global:
  scrape_interval: 1m

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'navidrome'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["navidrome:4533"]

  - job_name: 'traefik'
    scrape_interval: 1s
    static_configs:
      - targets: ["traefik:8080"]
  - job_name: 'jellyfin'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["jellyfin:8096"]
