services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    image: portainer/portainer-ce:2.33.5-alpine
    networks:
      - services
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/containers/portainer:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`${HOST}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "homepage.group=Monitoring and access control"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Docker monitor"
networks:
  services:
    name: services
    external: true
