libnss_ldap:
    - question: "shared/ldapns/base-dn"
      value: dc="{{ dc }}"
      vtype: string
    - question: "libnss-ldap/rootbinddn"
      value: cn=admin,dc="{{ dc }}"
      vtype: string
    - question: "libnss-ldap/dblogin"
      value: "false"
      vtype: boolean
    - question: "libnss-ldap/confperm" 
      value: false
      vtype: boolean
    - question: "libnss-ldap/dbrootlogin" 
      value: false 
      vtype: boolean
    - question: "shared/ldapns/ldap_version" 
      value: 3 
      vtype: select
    - question: "libnss-ldap/rootbinddn" 
      value: "cn=admin" 
      vtype: string
    - question: "shared/ldapns/ldap-server" 
      value: "ldap://{{ address }}"
      vtype: string
    - question: "libnss-ldap/override" 
      value: true 
      vtype: boolean
    - question: "libnss-ldap/nsswitch" 
      value: "" 
      vtype: string

libnss_ldap_password:
    - question: "libnss-ldap/rootbindpw"
      value: "{{ pwd }}"

libpam_ldap:
    - question: "shared/ldapns/base-dn"
      value: dc="{{ dc }}" 
      vtype: string
    - question: "libpam-ldap/pam_password"
      value: "crypt"
      vtype: string
    - question: "libpam-ldap/dblogin" 
      value: false
      vtype: boolean
    - question: "libpam-ldap/dbrootlogin"
      value: true
      vtype: boolean
    - question: "libpam-ldap/rootbinddn"
      value: "cn=admin,dc={{ dc }}" 
      vtype: string
    - question: "shared/ldapns/ldap-server"
      value: ldap://"{{ address }}"
      vtype: string
    - question: "shared/ldapns/ldap_version"
      value: 3
      vtype: select

libpam_ldap_password:
    - question: "libpam-ldap/rootbindpw"
      value: "{{ pwd }}"
      vtype: "password"

files:
    - src: "../files/nsswitch.conf"
      dest: "/etc/nsswitch.conf"
    - src: "../files/ldap.conf"
      dest: "/etc/ldap/ldap.conf"

      