services:
  dozzle:
    image: amir20/dozzle:v9.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - services
    labels:
      # traefik labels
      - "traefik.enable=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      # default entrypoint with authelia authentincation
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.routers.dozzle.rule=Host(`${HOST}`)"
      # homepage labels
      - "homepage.group=Monitoring and access control"
      - "homepage.name=Dozzle"
      - "homepage.icon=dozzle.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Container management"
      # diun labels
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.sort_tags=semver"
      - "diun.max_tags=3"
networks:
  services:
    name: services
    external: true
