---
services:
  traefik:
    restart: unless-stopped
    container_name: traefik
    networks:
      - services
    # The official v3 Traefik docker image
    image: traefik:v3.4
    # Enables the web UI and tells Traefik to listen to docker
    environment:
    - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.docker.network=services"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.minecraft.address=:25565/tcp"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${CLOUDFLARE_ACCOUNT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      # HTTP port
      - "80:80"
      # HTTPS port
      - "443:443"
      # Minecraft port
      - "25565:25565"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-letsencrypt:/letsencrypt

    labels:
      # expose dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${HOST}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      #- "traefik.http.routers.dashboard.middlewares=authelia-basicauth@docker"
      # block middleware
      - "traefik.http.middlewares.deny.IPAllowList.sourceRange=127.0.0.1/32"

      # homepage labels
      - "homepage.group=Monitoring and access control"
      - "homepage.name=Traefik"
      - "homepage.icon=traefik.svg"
      - "homepage.href=https://${HOST}/dashboard/"
      - "homepage.description=Reverse proxy"

      # diun labels
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.sort_tags=semver"
      - "diun.max_tags=3"

networks:
  services:
    name: services
    driver: bridge

volumes:
  traefik-letsencrypt:
    name: traefik-letsencrypt
