---
services:
  adguard:
    restart: unless-stopped
    container_name: adguard
    image: adguard/adguardhome:v0.107.65
    networks:
      - services
      - adguard
    ports:
      - "53:53/udp"
    volumes:
      - "/mnt/containers/adguard:/opt/adguardhome/work"
      - "/etc/adguard:/opt/adguardhome/conf"
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=websecure
      - "traefik.http.routers.adguard.rule=Host(`${HOST}`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
      - "traefik.http.routers.adguard.tls.certresolver=myresolver"

      - "homepage.group=Personal Cloud"
      - "homepage.name=Adguard"
      - "homepage.icon=adguard-home.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=dns forwarder"

  adguard-exporter:
    container_name: adguard-exporter
    restart: unless-stopped
    image: ghcr.io/henrywhitaker3/adguard-exporter:v1.2.1
    environment:
      - "ADGUARD_SERVERS=http://adguard"
      - 'ADGUARD_USERNAMES=${USERNAME}'
      - 'ADGUARD_PASSWORDS=${PASSWORD}'
      - 'INTERVAL=15s'
    networks:
      - monitoring
      - adguard

networks:
  services:
    name: services
    external: true
  monitoring:
    name: monitoring
    external: true
  adguard:
    name: adguard
    driver: bridge
